"""Fundamental analysis agent models."""

from pydantic import BaseModel, Field


class CompanyProfile(BaseModel, frozen=True):
    """Company overview from yfinance + RAG (Step 1 output)."""
    ticker: str
    name: str
    sector: str
    industry: str
    description: str
    market_cap: float | None = None
    pe_ratio: float | None = None
    revenue_growth: float | None = None


class AnalysisTask(BaseModel, frozen=True):
    """A single analytical task generated by the planner LLM (Step 2)."""
    task_id: str
    description: str
    rag_query: str
    weight: float = Field(..., gt=0.0, le=1.0)


class SubConclusion(BaseModel, frozen=True):
    """Result from executing a single AnalysisTask (Step 3)."""
    task_id: str
    conclusion: str
    supporting_evidence: list[str] = Field(default_factory=list)
    sentiment_score: float = Field(..., ge=-1.0, le=1.0)
    confidence: float = Field(..., ge=0.0, le=1.0)
